apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fargateprofiles.massrelay.io
spec:
  group: massrelay.io
  names:
    kind: FargateProfile
    listKind: FargateProfileList
    plural: fargateprofiles
    singular: fargateprofile
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: FargateProfile is the Schema for the fargateprofiles API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FargateProfileSpec defines the desired state of FargateProfile
          properties:
            name:
              description: Name of the Fargate profile. Maps to the https://docs.aws.amazon.com/eks/latest/APIReference/API_FargateProfile.html#AmazonEKS-Type-FargateProfile-fargateProfileName
                field in the AWS API.
              type: string
            podExecutionRoleArn:
              description: The Amazon Resource Name (ARN) of the pod execution role
                to use for pods that match the selectors in the Fargate profile. The
                pod execution role allows Fargate infrastructure to register with
                your cluster as a node, and it provides read access to Amazon ECR
                image repositories. For more information, see Pod Execution Role (https://docs.aws.amazon.com/eks/latest/userguide/pod-execution-role.html)
                in the Amazon EKS User Guide.
              type: string
            selectors:
              description: The selectors to match for pods to use this Fargate profile.
                Each selector must have an associated namespace. Optionally, you can
                also specify labels for a namespace. You may specify up to five selectors
                in a Fargate profile.
              items:
                description: FargateProfileSelector mirrors the EKS Fargate API's
                  profile selector.
                properties:
                  labels:
                    additionalProperties:
                      description: LabelValue is a type used to satisfy CRD generator
                      type: string
                    description: The Kubernetes labels that the selector should match.
                      A pod must contain all of the labels that are specified in the
                      selector for it to be considered a match.
                    type: object
                  namespace:
                    description: The Kubernetes namespace that the selector should
                      match.
                    type: string
                required:
                - labels
                - namespace
                type: object
              type: array
            subnets:
              description: The IDs of subnets to launch your pods into. At this time,
                pods running on Fargate are not assigned public IP addresses, so only
                private subnets (with no direct route to an Internet Gateway) are
                accepted for this parameter.
              items:
                type: string
              type: array
            tags:
              additionalProperties:
                description: TagValue is a value used to satisfy the CRD generator
                type: string
              description: The metadata to apply to the Fargate profile to assist
                with categorization and organization. Each tag consists of a key and
                an optional value, both of which you define. Fargate profile tags
                do not propagate to any other resources associated with the Fargate
                profile, such as the pods that are scheduled with it.
              type: object
          required:
          - name
          - podExecutionRoleArn
          - selectors
          - subnets
          - tags
          type: object
        status:
          description: FargateProfileStatus defines the observed state of FargateProfile
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
