kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mass-relay
subjects:
- kind: ServiceAccount
  name: mass-relay
roleRef:
  kind: Role
  name: mass-relay
  apiGroup: rbac.authorization.k8s.io
